hyrise/sql-parser

src/lib/sqllib.h, src/parser/SQLParser.cpp
* `typedef unsigned int uint`
`uint` isn't a standard type - `unsigned int` is.
* add missing `#include <string>`
clang on mac complains about this
=> fix build on mac

src/lib/statements/SQLStatement.h
`SQLStatementList::addStatement` takes over ownership of added `SQLStatement*`. It is invoked here:
https://github.com/hyrise/sql-parser/blob/b1622ce71dfbfa37198827043e494f9b61be0ef5/src/parser/bison_parser.y#L235
When destroying `SQLStatementList`, the `SQLStatement*` owned by it should also be freed.
=> fix memory leak in SQLStatementList

src/parser/bison_parser.y, src/sql/PrepareStatement.h, src/sqlhelper.cpp, src/sqlhelper.h
`uint` is only available on Linux. Other than this, there seems to be no other dependency on the compiler. Replacing `unit` with `uintmax_t` (available since c++11 standard, ref: http://en.cppreference.com/w/cpp/types/integer)
=> Use C++ standard int types to allow compilation with clang++ also

.travis.yml, src/SQLParser.cpp, src/SQLParserResult.cpp, src/SQLParserResult.h, src/parser/Makefile, src/parser/bison_parser.cpp, src/parser/bison_parser.h, src/parser/bison_parser.y, src/sql/CreateStatement.h, src/sql/DropStatement.h, src/sql/ExecuteStatement.h, src/sql/Expr.cpp, src/sql/InsertStatement.h, src/sql/PrepareStatement.h, src/sql/statements.cpp, test/lib/helper.h, test/lib/select.cpp, test/lib/test.cpp, test/lib/test.h, test/lib/valid_queries.sql, test/sql_grammar_test.cpp, test/sql_tests.cpp, test/test.sh
Includes:
* Fixes several memory leaks in the parser.
* Valgrind used for leak detection.
* Adds automatic leak detection to CI script (using valgrind)
* Fixes CI builds to always use bison 3.0.4
Note: Inspired by @ahalam 's PR #20. Thanks for your work!
=> Fix memory leaks

example/example.cpp, src/util/sqlhelper.cpp
This PR fixes two compiler warnings regarding format specifiers (macOS / clang):
```c++
src/util/sqlhelper.cpp:14:52: warning:
format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
printf("%s%ld  \n", indent(numIndent).c_str(), val);
~~~                                  ^~~
%lld
sql-parser/src/util/sqlhelper.cpp:29:50: warning:
format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
printf("%s%lu\n", indent(numIndent).c_str(), val);
~~~                                ^~~
%llu
=> Fix: use correct format specifiers for int64

.gitignore, src/parser/bison_parser.cpp, src/parser/bison_parser.h, src/parser/bison_parser.y, src/parser/flex_lexer.cpp, src/parser/flex_lexer.h, src/sql/Expr.cpp, src/sql/Expr.h, src/util/sqlhelper.cpp, test/prepare_tests.cpp, test/select_tests.cpp, test/sql_tests.cpp
This PR splits up `kOpSimple`, which was being used to describe operators that can be represented as a single char. The advantage of splitting those up is that we can more easily differentiate between them and do not need to compare both the type and the character.
=> Add enum types for formerly 'simple' operands

src/util/sqlhelper.cpp
The [Expr::makeFunctionRef](https://github.com/hyrise/sql-parser/blob/fe35651bb5de1e7ca59d22c11359a149a45f19d3/src/sql/Expr.cpp#L108) uses `exprList` not `expr` to store expressions:  
```
Expr* Expr::makeFunctionRef(char* func_name, std::vector<Expr*>* exprList, bool distinct) {
Expr* e = new Expr(kExprFunctionRef);
e->name = func_name;
e->exprList = exprList;
e->distinct = distinct;
return e;
}
```
So during print [kExprFunctionRef expression](https://github.com/hyrise/sql-parser/blob/fe35651bb5de1e7ca59d22c11359a149a45f19d3/src/util/sqlhelper.cpp#L101):  
```
case kExprFunctionRef:
inprint(expr->name, numIndent);
inprint(expr->expr->name, numIndent + 1);
break;
```
`expr->expr` is a `nullptr`, and will cause program crash.
=> Fix bug in print kExprFunctionRef expression.

.travis.yml, Makefile, example/Makefile, src/parser/bison_parser.cpp, src/parser/bison_parser.h, src/parser/flex_lexer.cpp, src/parser/flex_lexer.h
In C++1z the `register` keyword was removed. Older versions of flex still use it, and the Makefile disabled those warnings.
In this PR, we switch to compile with C++1z and an up-to-date version of flex is used to compile the parser.
=> Do not allow deprecated features for flex

src/parser/bison_parser.y, src/parser/flex_lexer.l, test/select_tests.cpp
This change allows '==' as operator for test of equality, like sqlite allows.
Although this is not according to the standard, it should be allowed here as sqlite is in widespread use.
See also: https://sqlite.org/lang_expr.html#collateop
=> Allow '==' for operator equals

src/parser/flex_lexer.cpp, src/parser/flex_lexer.h, src/parser/flex_lexer.l
This should fix multi-threaded parsing. Not a clean solution, I am guessing the following block should be a single, state-less pattern? @mrks
```
\'                          { BEGIN singlequotedstring; strbuf = std::stringstream{}; }
<singlequotedstring>\'\'    { strbuf << '\''; }
<singlequotedstring>[^']*   { strbuf << yytext; }
<singlequotedstring>\'      { BEGIN 0; yylval->sval = strdup(strbuf.str().c_str()); return SQL_STRING; }
<singlequotedstring><<EOF>> { fprintf(stderr, "[SQL-Lexer-Error] Unterminated string\n"); return 0; }
```
Anyway, the following hyrise playground does not crash anymore, so Toni should be able to work with this for the time being.
```c++
#include <iostream>
#include <thread>
#include "types.hpp"
#include "tpch/tpch_queries.hpp"
#include "SQLParser.h"
using …
```
=> Fix multi-threaded parsing

Makefile
Sort the input file list
so that `libsqlparser.so.1` builds in a reproducible way
in spite of indeterministic filesystem readdir order.
See https://reproducible-builds.org/ for why this is good.
I tested that the other `find` result orders do not matter. Only .o file order in `LIB_OBJ` matters for the result.
This PR was done while working on reproducible builds for openSUSE.
also filed at https://github.com/envoyproxy/sql-parser/pull/1
=> Sort the input file list

hyrise/benchmark/benchmark.py, src/parser/keywordlist_generator.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
=> Use print() function in both Python 2 and Python 3

src/parser/Makefile
Some Linux distributions (e.g. Centos) don't have bc installed by
default. And some (e.g Centos 8) don't have binary packages for it
available either. It's safer to use awk instead of bc to check
versions of bison and flex in the parser Makefile.
Closes #144
=> Use awk to check versions

README.md
c++17 is required to build the project. The minimum versions of gcc
and clang that support c++17 are 5 (for both compilers).
Closes #148
=> Fix compiler version requirements in readme

src/sql/Expr.cpp, src/sql/Expr.h, src/util/sqlhelper.cpp, test/select_tests.cpp
Previously, printing a cast/extract expression caused a segfault as the logic for `kExprFunctionRef` prints the `exprList` field which is not set for those types. Fixed this by adding customized printing logic for those expression types.
=> Fix segfault on printing cast/extract exprs

src/util/sqlhelper.cpp, src/util/sqlhelper.h
Issue is in sqlhelper.cpp, method printSelectStatementInfo.
=> Fixing print ORDER BY bug: only first sort column was printed.

README.md
Update the batch. It currently directs to travis-ci.org, which is no longer the active Travis site, and the redirect does not work.
=> Update Travis CI batch

.travis.yml, format.sh, src/parser/Makefile, test/test.sh
This PR updates the Makefile and the format script to support the different brew library path on ARM Macs. Furthermore, it adds a macOS stage to the CI pipeline.
=> Update Toolchain for ARM Macs and add macOS CI stage

src/sql/CreateStatement.cpp, src/sql/CreateStatement.h, src/sql/statements.cpp
A compile error occurs when including the `"SQLParser.h"` in another project. (sql_parser as third-party)
```
/thirdparty/sql-parser/src/sql/CreateStatement.h:74:67: error: 'dynamic_cast' not permitted with '-fno-rtti'
74 | ynamic_cast<ColumnDefinition*>(tableElem)) {
|                                         ^
/thirdparty/sql-parser/src/sql/CreateStatement.h:76:82: error: 'dynamic_cast' not permitted with '-fno-rtti'
76 | dynamic_cast<TableConstraint*>(tableElem)) {
|                                         ^
```
Separate the declaration and definition of the `setColumnDefsAndConstraints` should fix this.
=> Fix the `'dynamic_cast' not permitted with '-fno-rtti'` error when integrated with LLVM/MLIR.

src/parser/bison_parser.cpp, src/parser/bison_parser.y, src/parser/flex_lexer.cpp, src/parser/flex_lexer.h, src/parser/flex_lexer.l
=> Correctly deallocate string vectors

.github/workflows/ci.yml
In #245, we noticed that the Github checkout action now uses a Node.js version that is incompatible with our gcc-6/Ubuntu-18.04 stage. Thus, we pull the code manually for this stage.
=> Fix CI build for Ubuntu 18.04

.github/workflows/ci.yml
In #248, we noticed that manually retrieving the code in the gcc-6 action stage does not work for PRs from forks. This PR fixes this issue.
The problem is that in general, the repo referenced by GitHub's contexts and environment variables is the (target) repo where the PR is issued. For PRs from forks, this is still our base repo and not the fork. However, we can access a clone's URL from the HEAD information if the event triggering the action is a PR (update).
Still, we keep a version that checks out the main branch if the action is triggered by a branch update because we still want to run the CI workflow for updates on our master branch.
Some helpful documentation:
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#defau …
=> Fix Cloning in CI for Forks

.github/workflows/ci.yml
Update the CI workflow to use the most recent GCC and clang versions available on Ubuntu 24.04.
=> Update compiler versions in CI workflow
